const ACTIONS = {
	SAVE_FETCHED_JOBS: Symbol('SAVE_FETCHED_JOBS'),
	SAVE_FETCHED_STATES: Symbol('SAVE_FETCHED_STATES'),
	SAVE_FETCHED_POPULATION: Symbol('SAVE_FETCHED_POPULATION'),
	INSERT_PACKAGE_SEARCH_RESULTS: Symbol('INSERT_PACKAGE_SEARCH_RESULTS'),
	CLEAR_PACKAGE_SEARCH_RESULTS: Symbol('CLEAR_PACKAGE_SEARCH_RESULTS'),
	SHOW_LOADER: Symbol('SHOW_LOADER'),
	HIDE_LOADER: Symbol('HIDE_LOADER'),
	TOGGLE_MENU: Symbol('TOGGLE_MENU')
};

export default ACTIONS;
