const ACTIONS = {
	SAVE_FETCHED_JOBS: Symbol('SAVE_FETCHED_JOBS'),
	SAVE_FETCHED_STATES: Symbol('SAVE_FETCHED_STATES'),
	SAVE_FETCHED_POPULATION: Symbol('SAVE_FETCHED_POPULATION')
};

export default ACTIONS;
